// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protoc3.proto

package protoc3

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type M1_Enum_1 int32

const (
	M1_Enum_1_0 M1_Enum_1 = 0
	M1_Enum_1_1 M1_Enum_1 = 1
	M1_Enum_1_2 M1_Enum_1 = 2
)

var M1_Enum_1_name = map[int32]string{
	0: "Enum_1_0",
	1: "Enum_1_1",
	2: "Enum_1_2",
}

var M1_Enum_1_value = map[string]int32{
	"Enum_1_0": 0,
	"Enum_1_1": 1,
	"Enum_1_2": 2,
}

func (x M1_Enum_1) String() string {
	return proto.EnumName(M1_Enum_1_name, int32(x))
}

func (M1_Enum_1) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_80618194695df2dc, []int{0, 0}
}

type M1 struct {
	Str_1                string      `protobuf:"bytes,1,opt,name=str_1,json=str1,proto3" json:"str_1,omitempty"`
	Bytes_1              []byte      `protobuf:"bytes,2,opt,name=bytes_1,json=bytes1,proto3" json:"bytes_1,omitempty"`
	Int32_1              int32       `protobuf:"varint,3,opt,name=int32_1,json=int321,proto3" json:"int32_1,omitempty"`
	Int32_2              int32       `protobuf:"varint,4,opt,name=int32_2,json=int322,proto3" json:"int32_2,omitempty"`
	Uint32_1             uint32      `protobuf:"varint,5,opt,name=uint32_1,json=uint321,proto3" json:"uint32_1,omitempty"`
	Sint32_1             int32       `protobuf:"zigzag32,6,opt,name=sint32_1,json=sint321,proto3" json:"sint32_1,omitempty"`
	Sint32_2             int32       `protobuf:"zigzag32,7,opt,name=sint32_2,json=sint322,proto3" json:"sint32_2,omitempty"`
	Fixed32_1            uint32      `protobuf:"fixed32,8,opt,name=fixed32_1,json=fixed321,proto3" json:"fixed32_1,omitempty"`
	Fixed32_2            uint32      `protobuf:"fixed32,9,opt,name=fixed32_2,json=fixed322,proto3" json:"fixed32_2,omitempty"`
	Sfixed32_1           int32       `protobuf:"fixed32,10,opt,name=sfixed32_1,json=sfixed321,proto3" json:"sfixed32_1,omitempty"`
	Sfixed32_2           int32       `protobuf:"fixed32,11,opt,name=sfixed32_2,json=sfixed322,proto3" json:"sfixed32_2,omitempty"`
	Int64_1              int64       `protobuf:"varint,12,opt,name=int64_1,json=int641,proto3" json:"int64_1,omitempty"`
	Int64_2              int64       `protobuf:"varint,13,opt,name=int64_2,json=int642,proto3" json:"int64_2,omitempty"`
	Uint64_1             uint64      `protobuf:"varint,14,opt,name=uint64_1,json=uint641,proto3" json:"uint64_1,omitempty"`
	Sint64_1             int64       `protobuf:"zigzag64,15,opt,name=sint64_1,json=sint641,proto3" json:"sint64_1,omitempty"`
	Sint64_2             int64       `protobuf:"zigzag64,16,opt,name=sint64_2,json=sint642,proto3" json:"sint64_2,omitempty"`
	Fixed64_1            uint64      `protobuf:"fixed64,17,opt,name=fixed64_1,json=fixed641,proto3" json:"fixed64_1,omitempty"`
	Fixed64_2            uint64      `protobuf:"fixed64,18,opt,name=fixed64_2,json=fixed642,proto3" json:"fixed64_2,omitempty"`
	Sfixed64_1           int64       `protobuf:"fixed64,19,opt,name=sfixed64_1,json=sfixed641,proto3" json:"sfixed64_1,omitempty"`
	Sfixed64_2           int64       `protobuf:"fixed64,20,opt,name=sfixed64_2,json=sfixed642,proto3" json:"sfixed64_2,omitempty"`
	Bool_1               bool        `protobuf:"varint,21,opt,name=bool_1,json=bool1,proto3" json:"bool_1,omitempty"`
	Bool_2               bool        `protobuf:"varint,22,opt,name=bool_2,json=bool2,proto3" json:"bool_2,omitempty"`
	Float_1              float32     `protobuf:"fixed32,23,opt,name=float_1,json=float1,proto3" json:"float_1,omitempty"`
	Float_2              float32     `protobuf:"fixed32,24,opt,name=float_2,json=float2,proto3" json:"float_2,omitempty"`
	Double_1             float64     `protobuf:"fixed64,25,opt,name=double_1,json=double1,proto3" json:"double_1,omitempty"`
	Double_2             float64     `protobuf:"fixed64,26,opt,name=double_2,json=double2,proto3" json:"double_2,omitempty"`
	Enum_1               []M1_Enum_1 `protobuf:"varint,27,rep,packed,name=enum_1,json=enum1,proto3,enum=M1_Enum_1" json:"enum_1,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *M1) Reset()         { *m = M1{} }
func (m *M1) String() string { return proto.CompactTextString(m) }
func (*M1) ProtoMessage()    {}
func (*M1) Descriptor() ([]byte, []int) {
	return fileDescriptor_80618194695df2dc, []int{0}
}

func (m *M1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M1.Unmarshal(m, b)
}
func (m *M1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M1.Marshal(b, m, deterministic)
}
func (m *M1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M1.Merge(m, src)
}
func (m *M1) XXX_Size() int {
	return xxx_messageInfo_M1.Size(m)
}
func (m *M1) XXX_DiscardUnknown() {
	xxx_messageInfo_M1.DiscardUnknown(m)
}

var xxx_messageInfo_M1 proto.InternalMessageInfo

func (m *M1) GetStr_1() string {
	if m != nil {
		return m.Str_1
	}
	return ""
}

func (m *M1) GetBytes_1() []byte {
	if m != nil {
		return m.Bytes_1
	}
	return nil
}

func (m *M1) GetInt32_1() int32 {
	if m != nil {
		return m.Int32_1
	}
	return 0
}

func (m *M1) GetInt32_2() int32 {
	if m != nil {
		return m.Int32_2
	}
	return 0
}

func (m *M1) GetUint32_1() uint32 {
	if m != nil {
		return m.Uint32_1
	}
	return 0
}

func (m *M1) GetSint32_1() int32 {
	if m != nil {
		return m.Sint32_1
	}
	return 0
}

func (m *M1) GetSint32_2() int32 {
	if m != nil {
		return m.Sint32_2
	}
	return 0
}

func (m *M1) GetFixed32_1() uint32 {
	if m != nil {
		return m.Fixed32_1
	}
	return 0
}

func (m *M1) GetFixed32_2() uint32 {
	if m != nil {
		return m.Fixed32_2
	}
	return 0
}

func (m *M1) GetSfixed32_1() int32 {
	if m != nil {
		return m.Sfixed32_1
	}
	return 0
}

func (m *M1) GetSfixed32_2() int32 {
	if m != nil {
		return m.Sfixed32_2
	}
	return 0
}

func (m *M1) GetInt64_1() int64 {
	if m != nil {
		return m.Int64_1
	}
	return 0
}

func (m *M1) GetInt64_2() int64 {
	if m != nil {
		return m.Int64_2
	}
	return 0
}

func (m *M1) GetUint64_1() uint64 {
	if m != nil {
		return m.Uint64_1
	}
	return 0
}

func (m *M1) GetSint64_1() int64 {
	if m != nil {
		return m.Sint64_1
	}
	return 0
}

func (m *M1) GetSint64_2() int64 {
	if m != nil {
		return m.Sint64_2
	}
	return 0
}

func (m *M1) GetFixed64_1() uint64 {
	if m != nil {
		return m.Fixed64_1
	}
	return 0
}

func (m *M1) GetFixed64_2() uint64 {
	if m != nil {
		return m.Fixed64_2
	}
	return 0
}

func (m *M1) GetSfixed64_1() int64 {
	if m != nil {
		return m.Sfixed64_1
	}
	return 0
}

func (m *M1) GetSfixed64_2() int64 {
	if m != nil {
		return m.Sfixed64_2
	}
	return 0
}

func (m *M1) GetBool_1() bool {
	if m != nil {
		return m.Bool_1
	}
	return false
}

func (m *M1) GetBool_2() bool {
	if m != nil {
		return m.Bool_2
	}
	return false
}

func (m *M1) GetFloat_1() float32 {
	if m != nil {
		return m.Float_1
	}
	return 0
}

func (m *M1) GetFloat_2() float32 {
	if m != nil {
		return m.Float_2
	}
	return 0
}

func (m *M1) GetDouble_1() float64 {
	if m != nil {
		return m.Double_1
	}
	return 0
}

func (m *M1) GetDouble_2() float64 {
	if m != nil {
		return m.Double_2
	}
	return 0
}

func (m *M1) GetEnum_1() []M1_Enum_1 {
	if m != nil {
		return m.Enum_1
	}
	return nil
}

type M0 struct {
	M1                   []*M1    `protobuf:"bytes,1,rep,name=m1,proto3" json:"m1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M0) Reset()         { *m = M0{} }
func (m *M0) String() string { return proto.CompactTextString(m) }
func (*M0) ProtoMessage()    {}
func (*M0) Descriptor() ([]byte, []int) {
	return fileDescriptor_80618194695df2dc, []int{1}
}

func (m *M0) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M0.Unmarshal(m, b)
}
func (m *M0) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M0.Marshal(b, m, deterministic)
}
func (m *M0) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M0.Merge(m, src)
}
func (m *M0) XXX_Size() int {
	return xxx_messageInfo_M0.Size(m)
}
func (m *M0) XXX_DiscardUnknown() {
	xxx_messageInfo_M0.DiscardUnknown(m)
}

var xxx_messageInfo_M0 proto.InternalMessageInfo

func (m *M0) GetM1() []*M1 {
	if m != nil {
		return m.M1
	}
	return nil
}

func init() {
	proto.RegisterEnum("M1_Enum_1", M1_Enum_1_name, M1_Enum_1_value)
	proto.RegisterType((*M1)(nil), "M1")
	proto.RegisterType((*M0)(nil), "M0")
}

func init() { proto.RegisterFile("protoc3.proto", fileDescriptor_80618194695df2dc) }

var fileDescriptor_80618194695df2dc = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0xd3, 0xc1, 0x6e, 0x9b, 0x40,
	0x10, 0x06, 0xe0, 0x0e, 0x98, 0x05, 0x36, 0x76, 0x42, 0xd6, 0x4d, 0x33, 0x6e, 0x54, 0x69, 0xeb,
	0xd3, 0x9e, 0xac, 0xcc, 0x38, 0xca, 0x03, 0x54, 0xea, 0xd1, 0x97, 0x3d, 0xf6, 0xb2, 0xaa, 0x1b,
	0x47, 0x8a, 0x64, 0x9b, 0xca, 0x80, 0xd4, 0x3e, 0x48, 0xdf, 0xb7, 0x62, 0xc1, 0x66, 0x51, 0x4e,
	0xf0, 0xcf, 0xa7, 0xff, 0xf0, 0x23, 0x21, 0x67, 0xbf, 0x4f, 0x65, 0x5d, 0xfe, 0x5a, 0xaf, 0xfc,
	0x73, 0xf9, 0x4f, 0xc8, 0x68, 0x43, 0x6a, 0x2e, 0x93, 0xaa, 0x3e, 0x39, 0x42, 0xd0, 0x60, 0x72,
	0x3b, 0xa9, 0xea, 0x13, 0xa9, 0x7b, 0x99, 0x6e, 0xff, 0xd6, 0xbb, 0xca, 0x11, 0x46, 0x1a, 0xcc,
	0xd4, 0x0a, 0x1f, 0x3d, 0xbc, 0x1d, 0xeb, 0x35, 0x3b, 0xc2, 0x58, 0x83, 0x49, 0xac, 0xf0, 0x31,
	0x00, 0xc6, 0x49, 0x00, 0xac, 0x16, 0x32, 0x6b, 0xce, 0x95, 0x44, 0x83, 0x99, 0xd9, 0xb4, 0xe9,
	0x3b, 0x0b, 0x99, 0x55, 0x67, 0x12, 0x1a, 0xcc, 0xad, 0x4d, 0xab, 0x77, 0xc4, 0x98, 0x86, 0xc4,
	0xea, 0x41, 0xe6, 0xaf, 0x6f, 0x7f, 0x76, 0x2f, 0xbe, 0x96, 0x69, 0x30, 0xa9, 0xcd, 0xfa, 0x03,
	0x85, 0xc8, 0x98, 0x8f, 0x90, 0xd5, 0x17, 0x29, 0xab, 0xa1, 0x2a, 0x35, 0x98, 0x1b, 0x9b, 0x57,
	0x97, 0x6e, 0xc8, 0x8c, 0x57, 0x63, 0xe6, 0x7e, 0xe1, 0xf3, 0x93, 0x23, 0x9c, 0x6a, 0x30, 0xb1,
	0x5f, 0xf8, 0xfc, 0x44, 0x03, 0x30, 0xce, 0x02, 0xb8, 0x4c, 0xf7, 0x95, 0x6b, 0x0d, 0x66, 0xd2,
	0x4d, 0x6f, 0x3b, 0xfd, 0x3e, 0x4f, 0x37, 0x1a, 0x8c, 0xea, 0xf6, 0x8d, 0x89, 0xb1, 0x08, 0x69,
	0x98, 0xee, 0x6b, 0xb7, 0x1a, 0x8c, 0xe8, 0xd7, 0xb5, 0xbd, 0x00, 0x19, 0xd5, 0x08, 0x83, 0xe9,
	0xbe, 0x3a, 0xd7, 0x60, 0x8a, 0xf3, 0xb6, 0xb6, 0x1b, 0x32, 0xe3, 0xc7, 0x31, 0xb3, 0xba, 0x93,
	0x62, 0x5b, 0x96, 0x7b, 0x47, 0x78, 0xa7, 0xc1, 0x64, 0x36, 0x69, 0x13, 0x5d, 0xce, 0x8c, 0x9f,
	0x86, 0xb3, 0xff, 0x50, 0xaf, 0xfb, 0xf2, 0x67, 0xed, 0x08, 0xef, 0x35, 0x98, 0xc8, 0x0a, 0x1f,
	0x69, 0x00, 0x46, 0x0c, 0xc0, 0x7f, 0xa8, 0x97, 0xb2, 0xd9, 0xee, 0x77, 0x8e, 0x70, 0xa1, 0xc1,
	0x80, 0x4d, 0xbb, 0x4c, 0x01, 0x31, 0x7e, 0x0e, 0x89, 0xd5, 0x57, 0x29, 0x76, 0xc7, 0xe6, 0xe0,
	0x08, 0x1f, 0x74, 0x6c, 0xae, 0x59, 0xae, 0x36, 0xb4, 0xfa, 0xee, 0x2f, 0x36, 0x69, 0x85, 0x96,
	0x2c, 0x45, 0x77, 0x50, 0x53, 0x99, 0x75, 0x6f, 0xee, 0xb1, 0xf8, 0x10, 0x24, 0x2a, 0x20, 0x48,
	0x5c, 0x44, 0xcb, 0x85, 0x8c, 0x36, 0x8f, 0x6a, 0x2e, 0xa3, 0x43, 0xfb, 0x4f, 0xc4, 0xe6, 0x8a,
	0xe3, 0xd5, 0x86, 0x6c, 0x74, 0xa0, 0x6f, 0xf9, 0x8f, 0xb4, 0xff, 0x87, 0xb6, 0xc2, 0xbf, 0xac,
	0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0x71, 0xa6, 0x81, 0x95, 0x55, 0x03, 0x00, 0x00,
}
